call plug#begin()
  Plug 'ap/vim-css-color'
  Plug 'jiangmiao/auto-pairs'
call plug#end()

set number
set autoindent
set expandtab
set shiftround
set shiftwidth=2
set smarttab
set tabstop=2
set mouse=a
set dir=~/.cache/vim
set viminfo=
set backspace=indent,eol,start
